// Theme: 1 = Dark Gold  |  2 = Terracotta  |  3 = Noir Botanical
const THEME_OPTION: 1 | 2 | 3 = 1;

const themes = {
  1: {
    colors: {
      primary:      '#D4A853',
      primaryLight: '#1C2C1A',
      primaryDark:  '#B8922E',
      surface:      '#142016',
      background:   '#0C1A0E',
      border:       '#1E3020',
      textPrimary:  '#F5F0E8',
      textSecondary:'#7A9870',
      accent:       '#1A2A18',
      badge:        '#1E3020',
      badgeText:    '#D4A853',
      error:        '#E05252',
      errorLight:   '#2A1A1A',
      success:      '#4CAF50',
      overlay:      'rgba(0,0,0,0.72)',
      categoryAccent: {
        starter: '#1E2A18',
        main:    '#1A2C18',
        drink:   '#181E2C',
        dessert: '#2A1A2A',
      },
    },
    shadows: {
      card: {
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
        elevation: 5,
      },
      bar: {
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.5,
        shadowRadius: 12,
        elevation: 10,
      },
      sheet: {
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.6,
        shadowRadius: 20,
        elevation: 20,
      },
    },
  },

  2: {
    colors: {
      primary:      '#BF5830',
      primaryLight: '#FDF0E8',
      primaryDark:  '#9E4222',
      surface:      '#FFFFFF',
      background:   '#FBF7F2',
      border:       '#E8D8CC',
      textPrimary:  '#2C1A10',
      textSecondary:'#9C7A6A',
      accent:       '#F5EAE0',
      badge:        '#F0D8C8',
      badgeText:    '#9E4222',
      error:        '#C0392B',
      errorLight:   '#FCE8E8',
      success:      '#27AE60',
      overlay:      'rgba(44,26,16,0.5)',
      categoryAccent: {
        starter: '#FDF0E0',
        main:    '#F5EAE0',
        drink:   '#E8F0F5',
        dessert: '#F5E8F0',
      },
    },
    shadows: {
      card: {
        shadowColor: '#2C1A10',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
      },
      bar: {
        shadowColor: '#2C1A10',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 8,
      },
      sheet: {
        shadowColor: '#2C1A10',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.14,
        shadowRadius: 20,
        elevation: 16,
      },
    },
  },

  3: {
    colors: {
      primary:      '#6DBF3E',
      primaryLight: '#162418',
      primaryDark:  '#4E9A28',
      surface:      '#162416',
      background:   '#0F1A0D',
      border:       '#1E3418',
      textPrimary:  '#E8F5E4',
      textSecondary:'#5A8A50',
      accent:       '#1A2E18',
      badge:        '#1E3018',
      badgeText:    '#6DBF3E',
      error:        '#E05252',
      errorLight:   '#2A1A1A',
      success:      '#6DBF3E',
      overlay:      'rgba(0,0,0,0.72)',
      categoryAccent: {
        starter: '#1A2E18',
        main:    '#162A14',
        drink:   '#141E2E',
        dessert: '#221428',
      },
    },
    shadows: {
      card: {
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
        elevation: 5,
      },
      bar: {
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.5,
        shadowRadius: 12,
        elevation: 10,
      },
      sheet: {
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.6,
        shadowRadius: 20,
        elevation: 20,
      },
    },
  },
};

const selected = themes[THEME_OPTION];

export const theme = {
  colors: selected.colors,
  fontWeights: {
    regular: '400' as const,
    medium:  '500' as const,
    semi:    '600' as const,
    bold:    '700' as const,
  },
  radii: {
    xs:     4,
    sm:     8,
    md:     12,
    card:   16,
    lg:     20,
    pill:   999,
    button: 14,
    input:  12,
    image:  12,
  },
  spacing: {
    xs:   4,
    sm:   8,
    md:   12,
    lg:   16,
    xl:   20,
    xxl:  24,
    xxxl: 32,
  },
  shadows: selected.shadows,
  typography: {
    headingXL: { fontSize: 24, fontWeight: '700' as const, color: selected.colors.textPrimary },
    headingLG: { fontSize: 20, fontWeight: '700' as const, color: selected.colors.textPrimary },
    headingMD: { fontSize: 16, fontWeight: '600' as const, color: selected.colors.textPrimary },
    bodyMD:    { fontSize: 14, fontWeight: '400' as const, color: selected.colors.textPrimary },
    bodySM:    { fontSize: 12, fontWeight: '400' as const, color: selected.colors.textSecondary },
    labelMD:   { fontSize: 13, fontWeight: '600' as const, color: selected.colors.textPrimary },
    priceLG:   { fontSize: 15, fontWeight: '700' as const, color: selected.colors.primary },
    caption:   { fontSize: 11, fontWeight: '400' as const, color: selected.colors.textSecondary },
  },
} as const;
