export const theme = {
  colors: {
    primary:      '#BF5830',
    primaryLight: '#FDF0E8',
    primaryDark:  '#9E4222',
    surface:      '#FFFFFF',
    background:   '#FBF7F2',
    border:       '#E8D8CC',
    textPrimary:  '#2C1A10',
    textSecondary:'#9C7A6A',
    accent:       '#F5EAE0',
    badge:        '#F0D8C8',
    badgeText:    '#9E4222',
    error:        '#C0392B',
    errorLight:   '#FCE8E8',
    success:      '#27AE60',
    overlay:      'rgba(44,26,16,0.5)',
    categoryAccent: {
      starter: '#FDF0E0',
      main:    '#F5EAE0',
      drink:   '#E8F0F5',
      dessert: '#F5E8F0',
    },
  },
  fontWeights: {
    regular: '400' as const,
    medium:  '500' as const,
    semi:    '600' as const,
    bold:    '700' as const,
  },
  radii: {
    xs:     4,
    sm:     8,
    md:     12,
    card:   16,
    lg:     20,
    pill:   999,
    button: 14,
    input:  12,
    image:  12,
  },
  spacing: {
    xs:   4,
    sm:   8,
    md:   12,
    lg:   16,
    xl:   20,
    xxl:  24,
    xxxl: 32,
  },
  shadows: {
    card: {
      shadowColor: '#2C1A10',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 3,
    },
    bar: {
      shadowColor: '#2C1A10',
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 8,
    },
    sheet: {
      shadowColor: '#2C1A10',
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.14,
      shadowRadius: 20,
      elevation: 16,
    },
  },
  typography: {
    headingXL: { fontSize: 24, fontWeight: '700' as const, color: '#2C1A10' },
    headingLG: { fontSize: 20, fontWeight: '700' as const, color: '#2C1A10' },
    headingMD: { fontSize: 16, fontWeight: '600' as const, color: '#2C1A10' },
    bodyMD:    { fontSize: 14, fontWeight: '400' as const, color: '#2C1A10' },
    bodySM:    { fontSize: 12, fontWeight: '400' as const, color: '#9C7A6A' },
    labelMD:   { fontSize: 13, fontWeight: '600' as const, color: '#2C1A10' },
    priceLG:   { fontSize: 15, fontWeight: '700' as const, color: '#BF5830' },
    caption:   { fontSize: 11, fontWeight: '400' as const, color: '#9C7A6A' },
  },
} as const;
